# Generated by Django 3.2.9 on 2021-11-26 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_children', to='competition.comment', verbose_name='Parent comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='competition.photopost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='competition.photopost'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='full_image',
            field=models.ImageField(upload_to='photo/', verbose_name='Full image'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='previous_image',
            field=models.ImageField(default='placeholders/photo_placeholder.png', upload_to='photo/', verbose_name='Previous image'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publish date'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='state',
            field=django_fsm.FSMField(choices=[('new', 'new'), ('approved', 'approved'), ('rejected', 'rejected'), ('removed', 'removed')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update date'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='placeholders/avatar_placeholder.jpg', max_length=256),
        ),
    ]
