# Generated by Django 3.2.9 on 2021-11-13 11:55

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('competition', '0002_auto_20211112_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='state',
            field=django_fsm.FSMField(choices=[('new', 'new'), ('approved', 'approved'), ('rejected', 'rejected'), ('removed', 'removed')], default='new', max_length=50, verbose_name='Состояние поста'),
        ),
    ]
