# Generated by Django 3.2.9 on 2021-11-15 11:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_alter_user_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='user_thumbnail', verbose_name='Миниатура пользователя'),
        ),
    ]
