# Generated by Django 3.2.9 on 2021-11-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_alter_user_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_iamge',
            field=models.CharField(default='user_thumbnail/default.jpg', max_length=256),
        ),
    ]
