# Generated by Django 3.2.9 on 2021-11-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_user_profile_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_iamge',
            new_name='profile_image',
        ),
    ]
