# Generated by Django 3.2.9 on 2021-11-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_rename_profile_iamge_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
